CREATE TABLE [dbo].[IMPORT_ERROR] (
    [IMPORT_ID]     INT           NOT NULL,
    [ERROR_CODE]    VARCHAR (50)  NULL,
    [ERROR_MESSAGE] VARCHAR (512) NULL,
    CONSTRAINT [PK_IMPORT_ERROR] PRIMARY KEY CLUSTERED ([IMPORT_ID] ASC)
);


GO

