CREATE TABLE [dbo].[PRO_IMP_ORDER_20250626] (
    [CUSTOMER_ID]          INT           NOT NULL,
    [TRANSFERED]           INT           NOT NULL,
    [TRANSFERED_TIMESTAMP] DATETIME      NULL,
    [ACTIVITY]             CHAR (1)      NOT NULL,
    [ORDER_TYP]            INT           NOT NULL,
    [ORDER_NAME]           VARCHAR (20)  NOT NULL,
    [SCHEDULED_TIME]       DATETIME      NOT NULL,
    [RECEIVING_STATION]    VARCHAR (20)  NOT NULL,
    [WEIGHT_IN]            INT           NOT NULL,
    [WEIGHT_OUT]           INT           NOT NULL,
    [CUSTOMER_CODE]        VARCHAR (20)  NOT NULL,
    [LINE_CONTROL]         VARCHAR (20)  NULL,
    [SOURCE_GROUP]         INT           NULL,
    [TARGET_GROUP]         INT           NULL,
    [ORDER_DESCRIPTION]    VARCHAR (200) NULL,
    [TYPE_COMP_01]         VARCHAR (20)  NULL,
    [TYPE_COMP_02]         VARCHAR (20)  NULL,
    [TYPE_COMP_03]         VARCHAR (20)  NULL,
    [TYPE_COMP_04]         VARCHAR (20)  NULL,
    [TYPE_COMP_05]         VARCHAR (20)  NULL,
    [TYPE_COMP_06]         VARCHAR (20)  NULL,
    [TYPE_COMP_07]         VARCHAR (20)  NULL,
    [TYPE_COMP_08]         VARCHAR (20)  NULL,
    [TYPE_COMP_09]         VARCHAR (20)  NULL,
    [TYPE_COMP_10]         VARCHAR (20)  NULL,
    [TYPE_COMP_11]         VARCHAR (20)  NULL,
    [TYPE_COMP_12]         VARCHAR (20)  NULL,
    [TYPE_COMP_13]         VARCHAR (20)  NULL,
    [TYPE_COMP_14]         VARCHAR (20)  NULL,
    [PART_COMP_01]         INT           NULL,
    [PART_COMP_02]         INT           NULL,
    [PART_COMP_03]         INT           NULL,
    [PART_COMP_04]         INT           NULL,
    [PART_COMP_05]         INT           NULL,
    [PART_COMP_06]         INT           NULL,
    [PART_COMP_07]         INT           NULL,
    [PART_COMP_08]         INT           NULL,
    [PART_COMP_09]         INT           NULL,
    [PART_COMP_10]         INT           NULL,
    [PART_COMP_11]         INT           NULL,
    [PART_COMP_12]         INT           NULL,
    [PART_COMP_13]         INT           NULL,
    [PART_COMP_14]         INT           NULL,
    [TYPE_OPTIONAL_COMP]   VARCHAR (20)  NULL,
    [PART_OPTIONAL_COMP]   INT           NULL
);


GO

