CREATE TABLE [dbo].[PRO_EXP_INVENTORY] (
    [TRANSFERED]            INT          NOT NULL,
    [TRANSFERED_TIMESTAMP]  DATETIME     NULL,
    [MASTER_ID]             INT          NOT NULL,
    [LOT_NAME]              VARCHAR (20) NOT NULL,
    [ZONE]                  INT          NOT NULL,
    [CUSTOMER_CODE]         VARCHAR (20) NOT NULL,
    [AMOUNT]                INT          NOT NULL,
    [PRO_EXPORT_GENERAL_ID] INT          NOT NULL,
    [LOCATION]              VARCHAR (20) NULL,
    CONSTRAINT [PK_PRO_EXP_INVENTORY] PRIMARY KEY CLUSTERED ([PRO_EXPORT_GENERAL_ID] ASC)
);


GO

CREATE NONCLUSTERED INDEX [IX_PRO_EXP_INVENTORY]
    ON [dbo].[PRO_EXP_INVENTORY]([TRANSFERED] ASC);


GO

