CREATE TABLE [dbo].[tblDynamicLabelDataLog] (
    [ID]                      INT           IDENTITY (1, 1) NOT NULL,
    [Facility]                CHAR (3)      NOT NULL,
    [RecordType]              CHAR (1)      NOT NULL,
    [LabelKey]                NVARCHAR (50) NOT NULL,
    [PackagingLine]           CHAR (10)     NOT NULL,
    [ShopOrder]               INT           NULL,
    [ItemNumber]              VARCHAR (35)  NULL,
    [PalletID]                VARCHAR (9)   NULL,
    [Quantity]                INT           NULL,
    [MPProductionDate]        VARCHAR (20)  NULL,
    [ProductionDate]          SMALLDATETIME NOT NULL,
    [CreationTime]            DATETIME      NOT NULL,
    [LastUpdated]             DATETIME      CONSTRAINT [DF_tblDynamicLabelDataLog_LastUpdated] DEFAULT ('') NOT NULL,
    [Operator]                VARCHAR (50)  NOT NULL,
    [ItemDesc1]               VARCHAR (50)  NULL,
    [ItemDesc2]               VARCHAR (50)  NULL,
    [ItemDesc3]               VARCHAR (50)  NULL,
    [SCCCode]                 VARCHAR (14)  NULL,
    [UPCCode]                 VARCHAR (14)  NULL,
    [DomicileText1]           VARCHAR (24)  NULL,
    [DomicileText2]           VARCHAR (24)  NULL,
    [DomicileText3]           VARCHAR (24)  NULL,
    [DomicileText4]           VARCHAR (24)  NULL,
    [DomicileText5]           VARCHAR (24)  NULL,
    [DomicileText6]           VARCHAR (24)  NULL,
    [NetWeight]               VARCHAR (10)  NULL,
    [PackSize]                VARCHAR (12)  NULL,
    [ProductionShelfLifeDays] INT           NULL,
    [PreFmtProductionDate]    VARCHAR (50)  NULL,
    [PreFmtExpiryDate]        VARCHAR (50)  NULL,
    [CasePalletFmt1]          VARCHAR (25)  NULL,
    [CasePalletFmt2]          VARCHAR (25)  NULL,
    [CasePalletFmt3]          VARCHAR (25)  NULL,
    [PackageCoderFmt1]        VARCHAR (25)  NULL,
    [PackageCoderFmt2]        VARCHAR (25)  NULL,
    [PackageCoderFmt3]        VARCHAR (25)  NULL,
    [FilterCoderFmt]          VARCHAR (25)  NULL,
    [LotID]                   VARCHAR (25)  NOT NULL,
    [CaseLabelFmt1]           VARCHAR (25)  NULL,
    [CaseLabelFmt2]           VARCHAR (25)  NULL,
    [CaseLabelFmt3]           VARCHAR (25)  NULL,
    [Expr1]                   VARCHAR (35)  NOT NULL,
    [OverrideItem]            VARCHAR (35)  NULL,
    [ProductionDateDescOnBox] VARCHAR (30)  NULL,
    [ExpiryDateDescOnBox]     VARCHAR (30)  NULL,
    [AdditionalText1]         VARCHAR (30)  NULL,
    [AdditionalText2]         VARCHAR (30)  NULL,
    [Operation]               NCHAR (10)    CONSTRAINT [DF_tblDynamicLabelDataLog_Operation] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_tblDynamicLabelDataLog] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO

