CREATE TABLE [dbo].[tblItemMaster_20241125] (
    [Facility]                CHAR (3)        NOT NULL,
    [ItemNumber]              VARCHAR (35)    NOT NULL,
    [ProductionShelfLifeDays] INT             NOT NULL,
    [LabelWeight]             DECIMAL (10, 3) NOT NULL,
    [LabelWeightUOM]          CHAR (2)        NOT NULL,
    [BagLengthRequired]       CHAR (1)        NOT NULL,
    [BagLength]               DECIMAL (4, 2)  NOT NULL,
    [LabelDateFmtCode]        CHAR (2)        NOT NULL,
    [PackagesPerSaleableUnit] DECIMAL (5)     NOT NULL,
    [SaleableUnitPerCase]     DECIMAL (5)     NOT NULL,
    [QtyPerPallet]            INT             NOT NULL,
    [SCCCode]                 VARCHAR (14)    NOT NULL,
    [UPCCode]                 VARCHAR (14)    NOT NULL,
    [OverrideItem]            VARCHAR (35)    NOT NULL,
    [ItemDesc1]               VARCHAR (50)    NOT NULL,
    [ItemDesc2]               VARCHAR (50)    NOT NULL,
    [ItemDesc3]               VARCHAR (50)    NULL,
    [PackSize]                VARCHAR (12)    NOT NULL,
    [NetWeight]               VARCHAR (10)    NOT NULL,
    [DomicileText1]           VARCHAR (24)    NOT NULL,
    [DomicileText2]           VARCHAR (24)    NOT NULL,
    [DomicileText3]           VARCHAR (24)    NOT NULL,
    [DomicileText4]           VARCHAR (24)    NOT NULL,
    [DomicileText5]           VARCHAR (24)    NOT NULL,
    [DomicileText6]           VARCHAR (24)    NOT NULL,
    [CaseLabelFmt1]           VARCHAR (25)    NOT NULL,
    [CaseLabelFmt2]           VARCHAR (25)    NOT NULL,
    [CaseLabelFmt3]           VARCHAR (25)    NOT NULL,
    [PackageCoderFmt1]        VARCHAR (25)    NOT NULL,
    [PackageCoderFmt2]        VARCHAR (25)    NOT NULL,
    [PackageCoderFmt3]        VARCHAR (25)    NOT NULL,
    [FilterCoderFmt]          VARCHAR (25)    NOT NULL,
    [ProductionDateDesc]      VARCHAR (30)    NULL,
    [ExpiryDateDesc]          VARCHAR (30)    NULL,
    [PrintSOLot]              CHAR (1)        NOT NULL,
    [DateToPrintFlag]         CHAR (1)        NOT NULL,
    [PrintCaseLabel]          CHAR (1)        NOT NULL,
    [Tie]                     INT             NOT NULL,
    [Tier]                    INT             NOT NULL,
    [ShipShelfLifeDays]       INT             NULL,
    [ItemType]                VARCHAR (10)    NOT NULL,
    [ItemMajorClass]          VARCHAR (10)    NOT NULL,
    [PalletCode]              CHAR (1)        NULL,
    [SlipSheet]               BIT             NULL,
    [PkgLabelDateFmtCode]     CHAR (2)        NULL,
    [StdCostPerLB]            DECIMAL (15, 5) NOT NULL,
    [GrsDepth]                DECIMAL (16, 8) NULL,
    [GrsHeight]               DECIMAL (16, 8) NULL,
    [GrsWidth]                DECIMAL (16, 8) NULL,
    [CaseLabelApplicator]     TINYINT         NULL,
    [InsertBrewerFilter]      BIT             NULL
);


GO

