CREATE TABLE [dbo].[tblItemLabelOvrr_202050225] (
    [BagLength]               DECIMAL (4, 2) NULL,
    [BagLengthRequired]       CHAR (1)       NULL,
    [CaseLabelDateFmtCode]    CHAR (2)       NULL,
    [CaseLabelFmt1]           VARCHAR (25)   NULL,
    [CaseLabelFmt2]           VARCHAR (25)   NULL,
    [CaseLabelFmt3]           VARCHAR (25)   NULL,
    [DateToPrintFlag]         CHAR (1)       NULL,
    [DomicileText1]           VARCHAR (24)   NULL,
    [DomicileText2]           VARCHAR (24)   NULL,
    [DomicileText3]           VARCHAR (24)   NULL,
    [DomicileText4]           VARCHAR (24)   NULL,
    [DomicileText5]           VARCHAR (24)   NULL,
    [DomicileText6]           VARCHAR (24)   NULL,
    [ExpiryDateDesc]          VARCHAR (30)   NULL,
    [Facility]                CHAR (3)       NOT NULL,
    [FilterCoderFmt]          VARCHAR (25)   NULL,
    [ItemDesc1]               VARCHAR (50)   NULL,
    [ItemDesc2]               VARCHAR (50)   NULL,
    [ItemDesc3]               VARCHAR (50)   NULL,
    [ItemNumber]              VARCHAR (35)   NOT NULL,
    [NetWeight]               VARCHAR (10)   NULL,
    [NetWeightUOM]            CHAR (2)       NULL,
    [OverrideItem]            VARCHAR (35)   NULL,
    [OvrDesc1Flag]            BIT            NOT NULL,
    [OvrNetWeightFlag]        BIT            NOT NULL,
    [OvrNetWeightUOMFlag]     BIT            NOT NULL,
    [OvrPackSizeFlag]         BIT            NOT NULL,
    [PackageCoderFmt1]        VARCHAR (25)   NULL,
    [PackageCoderFmt2]        VARCHAR (25)   NULL,
    [PackageCoderFmt3]        VARCHAR (25)   NULL,
    [PackSize]                VARCHAR (12)   NULL,
    [PalletCode]              CHAR (1)       NULL,
    [PkgLabelDateFmtCode]     CHAR (2)       NULL,
    [PrintCaseLabel]          CHAR (1)       NULL,
    [PrintSOLot]              CHAR (1)       NULL,
    [ProductionDateDesc]      VARCHAR (30)   NULL,
    [SlipSheet]               BIT            NULL,
    [UseSCCAsUPC]             CHAR (1)       NULL,
    [LastUpdatedBy]           VARCHAR (100)  NULL,
    [LastUpdatedAt]           DATETIME       NULL,
    [ProductionDateDescOnBox] VARCHAR (30)   NULL,
    [ExpiryDateDescOnBox]     VARCHAR (30)   NULL,
    [AdditionalText1]         VARCHAR (30)   NULL,
    [AdditionalText2]         VARCHAR (30)   NULL,
    [PalletLabelFmt]          VARCHAR (25)   NULL,
    [CaseLabelApplicator]     TINYINT        NULL,
    [InsertBrewerFilter]      BIT            NULL,
    [PlantCode]               VARCHAR (10)   NOT NULL
);


GO

