'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class MySettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
    
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As MySettings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("C$\PowerPlant\PowerPlant")>  _
    Public Property strPowerPlantFolder() As String
        Get
            Return CType(Me("strPowerPlantFolder"),String)
        End Get
        Set
            Me("strPowerPlantFolder") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Palletizer.exe,PowerPlant.exe")>  _
    Public Property strPowerPlantFiles() As String
        Get
            Return CType(Me("strPowerPlantFiles"),String)
        End Get
        Set
            Me("strPowerPlantFiles") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("C$\PowerPlant\DownTime")>  _
    Public Property strDownTimeFolder() As String
        Get
            Return CType(Me("strDownTimeFolder"),String)
        End Get
        Set
            Me("strDownTimeFolder") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("C$\PowerPlant\IPCInitialPgm")>  _
    Public Property strIPCInitialPgmFolder() As String
        Get
            Return CType(Me("strIPCInitialPgmFolder"),String)
        End Get
        Set
            Me("strIPCInitialPgmFolder") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("IPCInitialPgm.exe.config")>  _
    Public Property strIPCInitialPgmFiles() As String
        Get
            Return CType(Me("strIPCInitialPgmFiles"),String)
        End Get
        Set
            Me("strIPCInitialPgmFiles") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("C:\DeploymentLog\")>  _
    Public Property strLogFile() As String
        Get
            Return CType(Me("strLogFile"),String)
        End Get
        Set
            Me("strLogFile") = value
        End Set
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Data Source=MPHOPP01;Initial Catalog=PowerPlant_Deployment;Persist Security Info="& _ 
        "True;User ID=mpo;Password=mpopwd$1")>  _
    Public ReadOnly Property strConn() As String
        Get
            Return CType(Me("strConn"),String)
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Software\ODBC\ODBC.INI\ServerPowerPlant")>  _
    Public Property strDftRegSubKeyPath() As String
        Get
            Return CType(Me("strDftRegSubKeyPath"),String)
        End Get
        Set
            Me("strDftRegSubKeyPath") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Server")>  _
    Public Property strDftRegKeyName() As String
        Get
            Return CType(Me("strDftRegKeyName"),String)
        End Get
        Set
            Me("strDftRegKeyName") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("MPSPPP01")>  _
    Public Property strDftNewRegValue() As String
        Get
            Return CType(Me("strDftNewRegValue"),String)
        End Get
        Set
            Me("strDftNewRegValue") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("C:\ProbatClient")>  _
    Public Property strDftProbatClientSourceFolder() As String
        Get
            Return CType(Me("strDftProbatClientSourceFolder"),String)
        End Get
        Set
            Me("strDftProbatClientSourceFolder") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("C$\ProbatClient")>  _
    Public Property strDftProbatClientTargetFolder() As String
        Get
            Return CType(Me("strDftProbatClientTargetFolder"),String)
        End Get
        Set
            Me("strDftProbatClientTargetFolder") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property strDftProbatFiles() As String
        Get
            Return CType(Me("strDftProbatFiles"),String)
        End Get
        Set
            Me("strDftProbatFiles") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("C:\ProbatClient\ConfigureProbatClientRegistry.bat")>  _
    Public Property strDftCfgProbatRegistryBatchFile() As String
        Get
            Return CType(Me("strDftCfgProbatRegistryBatchFile"),String)
        End Get
        Set
            Me("strDftCfgProbatRegistryBatchFile") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("DownTime.exe")>  _
    Public Property strDownTimeFiles() As String
        Get
            Return CType(Me("strDownTimeFiles"),String)
        End Get
        Set
            Me("strDownTimeFiles") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\leebong\OneDrive - Mother Parkers Tea and Coffee\Home\PowerPlant Archive"& _ 
        "s\Power Plant\V6.40 OLSOV\DeploymentObjects")>  _
    Public Property strSourceFolder() As String
        Get
            Return CType(Me("strSourceFolder"),String)
        End Get
        Set
            Me("strSourceFolder") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\leebong\OneDrive - Mother Parkers Tea and Coffee\Home\PowerPlant Archive"& _ 
        "s\Power Plant\V6.40 OLSOV\Changes on Server")>  _
    Public Property strSourceFolderSQL() As String
        Get
            Return CType(Me("strSourceFolderSQL"),String)
        End Get
        Set
            Me("strSourceFolderSQL") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("C$\PowerPlant\PPWCFService")>  _
    Public Property strWCFFolder() As String
        Get
            Return CType(Me("strWCFFolder"),String)
        End Get
        Set
            Me("strWCFFolder") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("PPWCFService.dll")>  _
    Public Property strWCFFiles() As String
        Get
            Return CType(Me("strWCFFiles"),String)
        End Get
        Set
            Me("strWCFFiles") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("C$\PowerPlant\PPTCPServer")>  _
    Public Property strTCPFolder() As String
        Get
            Return CType(Me("strTCPFolder"),String)
        End Get
        Set
            Me("strTCPFolder") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("PPTCPServer.exe")>  _
    Public Property strTCPFiles() As String
        Get
            Return CType(Me("strTCPFiles"),String)
        End Get
        Set
            Me("strTCPFiles") = value
        End Set
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.PowerPlantIPCDeployment.MySettings
            Get
                Return Global.PowerPlantIPCDeployment.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
