CREATE VIEW [dbo].[PRO_EXP_ORDER_LOAD_G_VIEW]
AS
SELECT        TRANSFERED, TRANSFERED_TIMESTAMP, RECORDING_DATE, DESTINATION, BATCH_ID, ORDER_NAME, MASTER_ID, CUSTOMER_CODE, SOURCE, 
                         S_PRODUCT_ID, S_CUSTOMER_CODE, S_TYPE_CELL, S_EMPTY, WEIGHT, START_FLAG, END_FLAG, PRO_EXPORT_GENERAL_ID AS ID, LOCATION
FROM            dbo.PRO_EXP_ORDER_LOAD_G

GO

