CREATE VIEW [dbo].[PRO_EXP_ORDER_UNLOAD_R_VIEW]
AS
SELECT        TRANSFERED, TRANSFERED_TIMESTAMP, RECORDING_DATE, ORDER_NAME, BATCH_ID, S_MASTER_ID, SOURCE_NAME, S_CUSTOMER_CODE, DEST_NAME, 
                         D_MASTER_ID, D_CUSTOMER_CODE, WEIGHT, PRO_EXPORT_GENERAL_ID AS ID, LOCATION
FROM            dbo.PRO_EXP_ORDER_UNLOAD_R

GO

