CREATE VIEW [dbo].[PRO_EXP_INVENTORY_VIEW]
AS
SELECT        TRANSFERED, TRANSFERED_TIMESTAMP, MASTER_ID, LOT_NAME, ZONE, CUSTOMER_CODE, AMOUNT, PRO_EXPORT_GENERAL_ID AS ID, LOCATION
FROM            dbo.PRO_EXP_INVENTORY

GO

