CREATE VIEW [dbo].[PRO_EXP_REC_CH_VIEW]
AS
SELECT        TRANSFERED, TRANSFERED_TIMESTAMP, RECORDING_DATE, ZONE, ORDER_NAME, DELIVERY_NAME, LOT_NAME, WEIGHT, CUSTOMER_CODE, DESTINATION, 
                         PRO_EXPORT_GENERAL_ID AS ID, DATA_1, DATA_2, DATA_3, DATA_11, DATA_12, DATA_13
FROM            dbo.PRO_EXP_REC_CH

GO

