CREATE VIEW [dbo].[PRO_IMP_BLENDS_ERROR_VIEW]
AS
SELECT        dbo.PRO_IMP_BLENDS.CUSTOMER_ID AS ID, dbo.PRO_IMP_BLENDS.TRANSFERED, ISNULL(dbo.PRO_EXP_ERROR_CODE.ERROR_CODE, '') AS ERROR_CODE, 
                         ISNULL(dbo.PRO_EXP_ERROR_CODE.ERROR_TXT, '') AS message
FROM            dbo.PRO_IMP_BLENDS INNER JOIN
                         dbo.PRO_EXP_ERROR_CODE ON dbo.PRO_IMP_BLENDS.CUSTOMER_ID = dbo.PRO_EXP_ERROR_CODE.CUSTOMER_ID
WHERE        (dbo.PRO_IMP_BLENDS.TRANSFERED <> 0)

GO

