CREATE VIEW [dbo].[PRO_IMP_ORDER_ERROR_VIEW]
AS
SELECT        dbo.PRO_IMP_ORDER.CUSTOMER_ID AS ID, dbo.PRO_IMP_ORDER.TRANSFERED, ISNULL(dbo.PRO_EXP_ERROR_CODE.ERROR_CODE, '') AS ERROR_CODE, 
                         ISNULL(dbo.PRO_EXP_ERROR_CODE.ERROR_TXT, '') AS message
FROM            dbo.PRO_IMP_ORDER LEFT OUTER JOIN
                         dbo.PRO_EXP_ERROR_CODE ON dbo.PRO_IMP_ORDER.CUSTOMER_ID = dbo.PRO_EXP_ERROR_CODE.CUSTOMER_ID
WHERE        (dbo.PRO_IMP_ORDER.TRANSFERED <> 0)

GO

