CREATE VIEW [dbo].[PRO_IMP_ORDER_REC_ERROR_VIEW]
AS
SELECT        dbo.PRO_IMP_ORDER_REC.CUSTOMER_ID AS ID, dbo.PRO_IMP_ORDER_REC.TRANSFERED, ISNULL(dbo.PRO_EXP_ERROR_CODE.ERROR_CODE, '') 
                         AS ERROR_CODE, ISNULL(dbo.PRO_EXP_ERROR_CODE.ERROR_TXT, '') AS message
FROM            dbo.PRO_IMP_ORDER_REC LEFT OUTER JOIN
                         dbo.PRO_EXP_ERROR_CODE ON dbo.PRO_IMP_ORDER_REC.CUSTOMER_ID = dbo.PRO_EXP_ERROR_CODE.CUSTOMER_ID
WHERE        (dbo.PRO_IMP_ORDER_REC.TRANSFERED <> 0)

GO

