CREATE VIEW [dbo].[PRO_IMP_COMMAND_ERROR_VIEW]
AS
SELECT        dbo.PRO_IMP_COMMAND.CUSTOMER_ID AS ID, dbo.PRO_IMP_COMMAND.TRANSFERED, ISNULL(dbo.PRO_EXP_ERROR_CODE.ERROR_CODE, '') 
                         AS ERROR_CODE, ISNULL(dbo.PRO_EXP_ERROR_CODE.ERROR_TXT, '') AS message
FROM            dbo.PRO_IMP_COMMAND INNER JOIN
                         dbo.PRO_EXP_ERROR_CODE ON dbo.PRO_IMP_COMMAND.CUSTOMER_ID = dbo.PRO_EXP_ERROR_CODE.CUSTOMER_ID
WHERE        (dbo.PRO_IMP_COMMAND.TRANSFERED <> 0)

GO

